dist: trusty

language: node_js

node_js:
    - "8"
    - "10"
    - "11"
    - "12"

matrix:
    allow_failures:
        - node_js: "12"

before_script:
    - npm install

script:
    - npm run lint
    - npm test
    - npm run build

after_script:
    - npm install -g codecov
    - codecov
